### ISSUE TITLE
.gitignore contains dat/raw/*.xlsx

### ISSUE THREAD

**Issue by davipatti** [LloydSmithLab/h5n1-inactivation#1]
Hello

I'm trying to rerun your analysis but get this error when calling `make`:

```
make: *** No rule to make target 'dat/raw/data_63C.xlsx', needed by 'dat/cleaned/data.tsv'.  Stop.`
```

The .gitignore contains `dat/raw/*.xlsx`

**Comment by dylanhmorris** [comment]
Thanks very much for flagging this. Those files were meant to be un-`.gitignore`-d for publication, as the comment in the `.gitignore` suggests. Fixed by #3.
