### ISSUE TITLE
Duplicate rows in dat/cleaned/data.tsv

### ISSUE THREAD

**Issue by davipatti** [LloydSmithLab/h5n1-inactivation#2]
Hello

`dat/cleaned/data.tsv` contains some duplicate rows. For instance there are four rows that correspond to a log_dilution=0, replicate=1, temperature_celsius=63, timepoint_minutes=0.333... (Lines 2, 10, 18 and 26).

For these parameters, data for all log dilutions are duplicated 4 times.

Most other sets of parameters are also duplicated 4 times, but some have slight differences in well_status.

Are these duplicate rows intentional?

**Comment by dylanhmorris** [comment]
Thank you for the question and apologies for the lack of clarity. The groups of 4 rows are not duplicates. They hold measurements for each of 4 titration wells inoculated per dilution for each measured sample. This would have been clearer had the raw data been visible (thanks very much for flagging that in #1) or if the cleaned `data.tsv` file had a `well_id` column or similar. In #3 I have added a note to the `README` to clarify this.

**Comment by davipatti** [comment]
Thanks for the clarification!
